/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParaBDD;

import ClasesSecundarias.Coneccion;
import ClasesSecundarias.Calzado;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Inventario extends javax.swing.JDialog {

    DefaultTableModel modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    Coneccion cn = new Coneccion();
    PreparedStatement pst = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form Clientes
     */
    public Inventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void establecerModeloTabla() {
        jTable_Inventario.setModel(modeloTabla);
        modeloTabla.addColumn("Codigo");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Talla");
        modeloTabla.addColumn("Precio Venta");
        modeloTabla.addColumn("Stock");
    }

    public void cargarDatosCalzado() {
        Vector<Calzado> calzado = DatosCalzado();
        boolean existe = false;
        Object[] cal = new Object[6];
        for (int i = 0; i < calzado.size(); i++) {
            cal[0] = calzado.get(i).getId();
            cal[1] = calzado.get(i).getNombre();
            cal[2] = calzado.get(i).getMarca();
            cal[3] = calzado.get(i).getModelo();
            cal[4] = calzado.get(i).getTalla();
            cal[4] = calzado.get(i).getPrecio();
            cal[5] = calzado.get(i).getExistencia();

            for (int j = 0; j < jTable_Inventario.getRowCount(); j++) {
                if (cal[0].toString().equals(jTable_Inventario.getValueAt(j, 0))) {
                    existe = true;
                    break;
                } else {
                    existe = false;
                }
            }
            if (!existe) {
                modeloTabla.addRow(cal);
            }

        }
    }

    public Vector<Calzado> DatosCalzado() {
        Vector<Calzado> usuarios = new Vector<Calzado>();
        Calzado cal;
        try {

            cn.Conectar();
            st = cn.getConexion().createStatement();
            String sql = "select * from producto_calzado";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                cal = new Calzado();
                cal.setId(rs.getInt(1));
                cal.setNombre(rs.getString(2));
                cal.setMarca(rs.getString(3));
                cal.setModelo(rs.getString(4));
                cal.setTalla(rs.getString(5));
                cal.setPrecio(rs.getFloat(6));
                cal.setExistencia(rs.getInt(6));
                usuarios.add(cal);
            }
            st.close();
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error : " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (java.lang.NullPointerException ex1) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error : " + ex1.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return usuarios;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarCalzado = new javax.swing.JButton();
        btnModificarCalzado = new javax.swing.JButton();
        btnBuscarCalzado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Inventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAgregarCalzado.setText("AGREGAR");
        btnAgregarCalzado.setBorderPainted(false);
        btnAgregarCalzado.setContentAreaFilled(false);
        btnAgregarCalzado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCalzado.setIconTextGap(-3);
        btnAgregarCalzado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgregarCalzado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnModificarCalzado.setText("MODIFICAR");
        btnModificarCalzado.setBorderPainted(false);
        btnModificarCalzado.setContentAreaFilled(false);
        btnModificarCalzado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarCalzado.setIconTextGap(-3);
        btnModificarCalzado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModificarCalzado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnBuscarCalzado.setText("BUSCAR");
        btnBuscarCalzado.setBorderPainted(false);
        btnBuscarCalzado.setContentAreaFilled(false);
        btnBuscarCalzado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCalzado.setIconTextGap(-3);
        btnBuscarCalzado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBuscarCalzado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        jTable_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Marca", "Modelo", "Talla", "Precio Compra", "Precio Venta", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Inventario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarCalzado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarCalzado)
                        .addGap(224, 224, 224)
                        .addComponent(btnBuscarCalzado)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarCalzado)
                    .addComponent(btnAgregarCalzado)
                    .addComponent(btnModificarCalzado))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inventario dialog = new Inventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCalzado;
    private javax.swing.JButton btnBuscarCalzado;
    private javax.swing.JButton btnModificarCalzado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Inventario;
    // End of variables declaration//GEN-END:variables
}
