/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParaBDD;

import ClasesSecundarias.Cliente;
import ClasesSecundarias.Coneccion;
import ClasesSecundarias.Metodos;
import ClasesSecundarias.Usuario;
import Formularios.UsuariosIngreso;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Usuarios extends javax.swing.JDialog {

    DefaultTableModel modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    Coneccion cn = new Coneccion();
    PreparedStatement pst = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form Clientes
     */
    public Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        establecerModeloTabla();
        cargarDatosUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void establecerModeloTabla() {
        jTable_DatosUsuarios.setModel(modeloTabla);
        modeloTabla.addColumn("Cédula");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Dirección");
        modeloTabla.addColumn("Sueldo");
        modeloTabla.addColumn("Teléfono");
    }

    private void limpiarTabla() {
        for (int i = jTable_DatosUsuarios.getRowCount() - 1; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    public void actualizarClientes() {
        limpiarTabla();
        cargarDatosUsuarios();
    }

    private void actualizarUnDato() throws HeadlessException {
        // TODO add your handling code here:
        Cliente c = new Cliente();

        if (jTextField_ApeUsu.getText().equals("")
                || jTextField_NomUsu.getText().equals("")
                || jTextField_DirUsu.getText().equals("")
                || jTextField_TelUsu.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campos sin llenar", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Object[] datos = {jTextField_CedUsu.getText(), jTextField_NomUsu.getText(), jTextField_ApeUsu.getText(),
                jTextField_DirUsu.getText(), jTextField_SueUsu.getText(), jTextField_TelUsu.getText()};
            try {
                cn.Conectar();
                String sql = "UPDATE EMPLEADOS SET "
                        + "NOM_EMP = '" + datos[1].toString() + "' , "
                        + "APE_EMP = '" + datos[2].toString() + "' , "
                        + "DIR_EMP = '" + datos[3].toString() + "' , "
                        + "SUE_EMP =" + Double.valueOf(datos[4].toString()) + ", "
                        + "TEL_EMP = '" + datos[5].toString() + "' "
                        + "WHERE CED_EMP = '" + datos[0].toString() + "'";
                pst = cn.getConexion().prepareStatement(sql);
                pst.executeUpdate();
                limpiarCampos();
                cargarDatosUsuarios();
                deshabilitarComponentes();
                actualizarClientes();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al actualizar " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void cargarDatosUsuarios() {
        Vector<Usuario> usuarios = DatosUsuarios();
        boolean existe = false;
        Object usu[] = new Object[6];
        for (int i = 0; i < usuarios.size(); i++) {
            usu[0] = usuarios.get(i).getCedula();
            usu[1] = usuarios.get(i).getNombre();
            usu[2] = usuarios.get(i).getApellido();
            usu[3] = usuarios.get(i).getDireccion();
            usu[4] = usuarios.get(i).getSueldo();
            usu[5] = usuarios.get(i).getTelefono();

            for (int j = 0; j < jTable_DatosUsuarios.getRowCount(); j++) {
                if (usu[0].toString().equals(jTable_DatosUsuarios.getValueAt(j, 0))) {
                    existe = true;
                    break;
                } else {
                    existe = false;
                }
            }
            if (!existe) {
                modeloTabla.addRow(usu);
            }

        }
    }

    public Vector<Usuario> DatosUsuarios() {
        Vector<Usuario> usuarios = new Vector<Usuario>();
        Usuario usu;
        try {

            cn.Conectar();
            st = cn.getConexion().createStatement();
            String sql = "select * from empleados";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                usu = new Usuario();
                usu.setCedula(rs.getString(1));
                usu.setNombre(rs.getString(2));
                usu.setApellido(rs.getString(3));
                usu.setDireccion(rs.getString(4));
                usu.setSueldo(rs.getDouble(5));
                usu.setTelefono(rs.getString(6));
                usuarios.add(usu);
            }
            st.close();
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error : " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (java.lang.NullPointerException ex1) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error : " + ex1.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return usuarios;
    }

    public void buscarDato() {
        limpiarTabla();
        try {
            cn.Conectar();
            String consulta = "SELECT * FROM EMPLEADOS WHERE APE_EMP LIKE " + "'" + jTextField_Buscar.getText() + "_%'";
            st = cn.getConexion().prepareStatement(consulta);
            rs = st.executeQuery(consulta);
            String[] fila = new String[6];
            while (rs.next()) {
                fila[0] = rs.getString("CED_EMP");
                fila[1] = rs.getString("NOM_EMP");
                fila[2] = rs.getString("APE_EMP");
                fila[3] = rs.getString("DIR_EMP");
                fila[4] = String.valueOf(rs.getDouble("SUE_EMP"));
                fila[5] = rs.getString("TEL_EMP");
                modeloTabla.addRow(fila);
            }

            rs.close();
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error : " + ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void habilitarComponentes() {
        jTextField_ApeUsu.setEnabled(true);
        jTextField_NomUsu.setEnabled(true);
        jTextField_DirUsu.setEnabled(true);
        jTextField_TelUsu.setEnabled(true);
        jTextField_SueUsu.setEnabled(true);
    }

    public void deshabilitarComponentes() {
        jTextField_ApeUsu.setEnabled(false);
        jTextField_NomUsu.setEnabled(false);
        jTextField_DirUsu.setEnabled(false);
        jTextField_SueUsu.setEnabled(false);
        jTextField_TelUsu.setEnabled(false);
    }

    public void limpiarCampos() {
        jTextField_CedUsu.setText("");
        jTextField_ApeUsu.setText("");
        jTextField_NomUsu.setText("");
        jTextField_DirUsu.setText("");
        jTextField_SueUsu.setText("");
        jTextField_TelUsu.setText("");
    }

    private void mostrarValores() {
        // TODO add your handling code here:
        if (jTable_DatosUsuarios.getSelectedRow() != -1) {
            habilitarComponentes();
            int fila = jTable_DatosUsuarios.getSelectedRow();
            jTextField_CedUsu.setText(jTable_DatosUsuarios.getValueAt(fila, 0).toString());
            jTextField_NomUsu.setText(jTable_DatosUsuarios.getValueAt(fila, 1).toString());
            jTextField_ApeUsu.setText(jTable_DatosUsuarios.getValueAt(fila, 2).toString());
            jTextField_DirUsu.setText(jTable_DatosUsuarios.getValueAt(fila, 3).toString());
            jTextField_SueUsu.setText(jTable_DatosUsuarios.getValueAt(fila, 4).toString());
            jTextField_TelUsu.setText(jTable_DatosUsuarios.getValueAt(fila, 5).toString());
        } else {
            deshabilitarComponentes();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DatosUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_CedUsu = new javax.swing.JTextField();
        jTextField_NomUsu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ApeUsu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_DirUsu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_TelUsu = new javax.swing.JTextField();
        jTextField_Buscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_SueUsu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        jTable_DatosUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Dirección", "Teléfono", "Cargo", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_DatosUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DatosUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DatosUsuarios);

        jLabel1.setText("Cédula:");

        jTextField_CedUsu.setEnabled(false);

        jTextField_NomUsu.setEnabled(false);
        jTextField_NomUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NomUsuKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jTextField_ApeUsu.setEnabled(false);
        jTextField_ApeUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ApeUsuKeyTyped(evt);
            }
        });

        jLabel4.setText("Dirección:");

        jTextField_DirUsu.setEnabled(false);
        jTextField_DirUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DirUsuKeyTyped(evt);
            }
        });

        jLabel5.setText("Teléfono:");

        jTextField_TelUsu.setEnabled(false);
        jTextField_TelUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_TelUsuKeyTyped(evt);
            }
        });

        jTextField_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_BuscarKeyReleased(evt);
            }
        });

        jLabel6.setText("Buscar:");

        btnAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/boton_agregar_cliente_2.png"))); // NOI18N
        btnAgregarUsuario.setText("AGREGAR");
        btnAgregarUsuario.setBorderPainted(false);
        btnAgregarUsuario.setContentAreaFilled(false);
        btnAgregarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarUsuario.setIconTextGap(-3);
        btnAgregarUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/boton_agregar_cliente_3.png"))); // NOI18N
        btnAgregarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/boton_agregar_cliente_1.png"))); // NOI18N
        btnAgregarUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgregarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        btnModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/boton_editar_cliente_2.png"))); // NOI18N
        btnModificarUsuario.setText("MODIFICAR");
        btnModificarUsuario.setBorderPainted(false);
        btnModificarUsuario.setContentAreaFilled(false);
        btnModificarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarUsuario.setIconTextGap(-3);
        btnModificarUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/boton_editar_cliente_3.png"))); // NOI18N
        btnModificarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/boton_editar_cliente_1.png"))); // NOI18N
        btnModificarUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModificarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Sueldo:");

        jTextField_SueUsu.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_CedUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_NomUsu)
                                .addComponent(jTextField_ApeUsu)
                                .addComponent(jTextField_DirUsu)
                                .addComponent(jTextField_Buscar)
                                .addComponent(jTextField_TelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_SueUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarUsuario)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnAgregarUsuario)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_CedUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_NomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ApeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_DirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_SueUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_TelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnModificarUsuario)
                    .addComponent(btnAgregarUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        new UsuariosIngreso(null, true).setVisible(true);
        cargarDatosUsuarios();
        
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void jTextField_NomUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NomUsuKeyTyped
        // TODO add your handling code here:
        Metodos.validarLetras(evt, jTextField_NomUsu);
    }//GEN-LAST:event_jTextField_NomUsuKeyTyped

    private void jTextField_ApeUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ApeUsuKeyTyped
        // TODO add your handling code here:
        Metodos.validarLetras(evt, jTextField_ApeUsu);
    }//GEN-LAST:event_jTextField_ApeUsuKeyTyped

    private void jTextField_DirUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DirUsuKeyTyped
        // TODO add your handling code here:
        Metodos.validarLetras(evt, jTextField_DirUsu);
    }//GEN-LAST:event_jTextField_DirUsuKeyTyped

    private void jTextField_TelUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TelUsuKeyTyped
        // TODO add your handling code here:
        Metodos.validarTelefono(evt, jTextField_TelUsu);
    }//GEN-LAST:event_jTextField_TelUsuKeyTyped

    private void jTable_DatosUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DatosUsuariosMouseClicked
        // TODO add your handling code here:
        mostrarValores();
    }//GEN-LAST:event_jTable_DatosUsuariosMouseClicked

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        // TODO add your handling code here:
        actualizarUnDato();
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void jTextField_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BuscarKeyReleased
        buscarDato();
    }//GEN-LAST:event_jTextField_BuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuarios dialog = new Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DatosUsuarios;
    private javax.swing.JTextField jTextField_ApeUsu;
    private javax.swing.JTextField jTextField_Buscar;
    private javax.swing.JTextField jTextField_CedUsu;
    private javax.swing.JTextField jTextField_DirUsu;
    private javax.swing.JTextField jTextField_NomUsu;
    private javax.swing.JTextField jTextField_SueUsu;
    private javax.swing.JTextField jTextField_TelUsu;
    // End of variables declaration//GEN-END:variables
}
