/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesSecundarias.Coneccion;
import ClasesSecundarias.Metodos;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Proveedores extends javax.swing.JDialog {

    /**
     * Creates new form Proveedores
     */
    Coneccion cn = new Coneccion();
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    String codigo, nombre, direccion, telefono;
    ArrayList ListadoCodigosProveedores = new ArrayList();

    public Proveedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        deshabilitarCancelar();
    }

    public void deshabilitarCancelar() {
        boolean res;

        if (jTextField_Nom_Prov.getText().equals("")) {
            res = true;
        } else {
            res = false;
        }
        if (jTextField_Dir_Prov.getText().equals("")) {
            res = true;
        } else {
            res = false;
        }
        if (jTextField_Tel_Prov.getText().equals("")) {
            res = true;
        } else {
            res = false;
        }

        if (jTextField_Cod_Prov.getText().equals("")) {
            res = true;
        } else {
            res = false;
        }
        if (res) {
            jButton_Can_Prov.setEnabled(false);
        } else {
            jButton_Can_Prov.setEnabled(true);
        }
    }

    public boolean existeCodigoProveedor() throws SQLException {
        cn.Conectar();
        String usu = "";
        String codigo = jTextField_Cod_Prov.getText();
        String query = "Select * proveedores where ced_cli" + codigo + "";
        st = cn.getConexion().createStatement();
        rs = st.executeQuery(query);
        while (rs.next()) {
            usu = rs.getString("COD_PROV");
        }
        if (codigo.equalsIgnoreCase(usu)) {
            JOptionPane.showMessageDialog(null, "Proveedor ya EXITE");
            return false;
        } else {
            return false;
        }
    }

    public boolean validarDatos() {
        if (jTextField_Cod_Prov.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el código", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (jTextField_Nom_Prov.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (jTextField_Dir_Prov.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la direccion", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (jTextField_Tel_Prov.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de teléfono ", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    public void limpiarDatos() {
        jTextField_Cod_Prov.setText("");
        jTextField_Nom_Prov.setText("");
        jTextField_Dir_Prov.setText("");
        jTextField_Tel_Prov.setText("");
    }

    public void setearVariables() {
        codigo = jTextField_Cod_Prov.getText();
        nombre = jTextField_Nom_Prov.getText();
        direccion = jTextField_Dir_Prov.getText();
        telefono = jTextField_Tel_Prov.getText();
    }

    public void ingresoProveedoresBase() throws SQLException {
        if (validarDatos()) {
            setearVariables();
            cn.Conectar();
            pst = cn.getConexion().prepareStatement("insert into proveedores (COD_PROV,NOM_PROV,DIR_PROV, TEL_PROV) values(?,?.?.?)");
            pst.setString(1, codigo);
            pst.setString(2, nombre);
            pst.setString(3, direccion);
            pst.setString(4, telefono);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
            limpiarDatos();
            deshabilitarCancelar();
        } else {
            JOptionPane.showMessageDialog(null, "");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_Gua_Prov = new javax.swing.JButton();
        jButton_Can_Prov = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Cod_Prov = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Nom_Prov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Dir_Prov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Tel_Prov = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PROVEEDORES"));

        jButton_Gua_Prov.setText("Guardar");
        jButton_Gua_Prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Gua_ProvActionPerformed(evt);
            }
        });
        jButton_Gua_Prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton_Gua_ProvKeyTyped(evt);
            }
        });

        jButton_Can_Prov.setText("Cancelar");
        jButton_Can_Prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Can_ProvActionPerformed(evt);
            }
        });

        jLabel1.setText("Código del Proveedor:");

        jTextField_Cod_Prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cod_ProvKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jTextField_Nom_Prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Nom_ProvKeyTyped(evt);
            }
        });

        jLabel3.setText("Dirección:");

        jTextField_Dir_Prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Dir_ProvKeyTyped(evt);
            }
        });

        jLabel4.setText("Teléfono:");

        jTextField_Tel_Prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Tel_ProvKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Gua_Prov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Can_Prov)
                .addGap(341, 341, 341))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Cod_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nom_Prov, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextField_Dir_Prov))
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Tel_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Cod_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Tel_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Nom_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Dir_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Gua_Prov)
                    .addComponent(jButton_Can_Prov)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Gua_ProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Gua_ProvActionPerformed

        try {

            if (validarDatos()) {
                ingresoProveedoresBase();
            } else {

            }

        } catch (SQLException ex) {
            //Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_Gua_ProvActionPerformed

    private void jTextField_Cod_ProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cod_ProvKeyTyped
        deshabilitarCancelar();
    }//GEN-LAST:event_jTextField_Cod_ProvKeyTyped

    private void jTextField_Nom_ProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Nom_ProvKeyTyped
        deshabilitarCancelar();
        Metodos.validarLetras(evt, jTextField_Nom_Prov);
    }//GEN-LAST:event_jTextField_Nom_ProvKeyTyped

    private void jTextField_Dir_ProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Dir_ProvKeyTyped
        deshabilitarCancelar();
        Metodos.validarLetras(evt, jTextField_Dir_Prov);
    }//GEN-LAST:event_jTextField_Dir_ProvKeyTyped

    private void jTextField_Tel_ProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Tel_ProvKeyTyped
        deshabilitarCancelar();
        Metodos.validarTelefono(evt, jTextField_Tel_Prov);
    }//GEN-LAST:event_jTextField_Tel_ProvKeyTyped

    private void jButton_Gua_ProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_Gua_ProvKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Gua_ProvKeyTyped

    private void jButton_Can_ProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Can_ProvActionPerformed
        limpiarDatos();
        deshabilitarCancelar();
    }//GEN-LAST:event_jButton_Can_ProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Proveedores dialog = new Proveedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Can_Prov;
    private javax.swing.JButton jButton_Gua_Prov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Cod_Prov;
    private javax.swing.JTextField jTextField_Dir_Prov;
    private javax.swing.JTextField jTextField_Nom_Prov;
    private javax.swing.JTextField jTextField_Tel_Prov;
    // End of variables declaration//GEN-END:variables
}
